version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing Serverless
      - npm install --location=global serverless
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Installing source NPM dependencies
      - npm install
  build:
    commands:
      - echo Deployment started on `date`
      - echo Deploying with Serverless Framework
      - serverless deploy -s $ENV_NAME
  post_build:
    commands:
      - echo Deployment completed on `date`
